import 'package:flutter/material.dart';
import 'package:hive/hive.dart';

part 'user_preferences_model.g.dart'; // This will be generated by Hive

@HiveType(typeId: 0) // Unique typeId for this model
class UserPreferences {
  @HiveField(0)
  final ThemeMode themeMode;

  @HiveField(1)
  final String sortOption;

  UserPreferences({
    this.themeMode = ThemeMode.system,
    this.sortOption = 'date',
  });

  Map<String, dynamic> toMap() {
    return {
      'themeMode': themeMode.index,
      'sortOption': sortOption,
    };
  }

  factory UserPreferences.fromMap(Map<String, dynamic> map) {
    return UserPreferences(
      themeMode: ThemeMode.values[map['themeMode']],
      sortOption: map['sortOption'],
    );
  }
}